version: '3'
services:
  presidio-analyzer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-analyzer${TAG}
    build:
      context: ./presidio-analyzer
      args:
        - NAME=presidio-analyzer
        - NLP_CONF_FILE=conf/transformers.yaml
      dockerfile: Dockerfile.transformers
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
