version: '3'
services:
  presidio-analyzer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-analyzer${TAG}
    build:
      context: ./presidio-analyzer
      args:
        - NAME=presidio-analyzer
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
